# Generated by Django 5.1.4 on 2025-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('processed', models.BooleanField(default=False)),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
    ]
